### ISSUE TITLE
Install problem and some question

### ISSUE THREAD

**Issue by bby2729** [cid-harvard/py-ecomplexity#32]
Thank you for sharing. When installing the package, I found that lines 22 and 23 of the code setup.py were missing commas, and there was a gbk encoding problem in the Readme.txt. I deleted some of the abnormal characters and the installation could be expected. 
And during the final standardization, I found that the results I reproduced were inconsistent with the actual ones. This was because the degrees of freedom of the standard deviation used in ECI standardization were different. I think it is better to use n-1, not n.

**Comment by shreyasgm** [comment]
Thanks for the note. The `setup.py` issue was fixed in 254486d . There's only a README.md and no .txt file, and I haven't had any problems with encodings there.

The standardization procedure has been tested and is consistent with other efforts, so I don't see the issue. Please post a reproducible example with a more detailed explanation of the issue you're facing.
